[package]
name = "nimble"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version="0.5.1",features=["tls","json","secrets"]}
miette = "7.4.0"
serde = {version="1.0.216",features=["derive"]}
thiserror = "2.0.8"
chrono = "0.4.39"
tokio-postgres = "0.7.12"
serde_json = "1.0.134"
