[package]
name = "nimble"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version="0.5.1",features=["tls","json","secrets"]}
miette = "7.4.0"
serde = {version="1.0.216",features=["derive"]}
thiserror = "2.0.8"
